var express = require("express");
var axios = require("axios");
var cheerio = require("cheerio");
var mongoose = require("mongoose");
var exhbs = require("express-handlebars");
var app = express();
var databaseUrl = "scraper";
var collections = ["scrapedData"];
var MONGODB_URI = process.env.MONGODB_URI || "mongodb://localhost/mongoHeadlines";
mongoose.connect(MONGODB_URI);